version: '3.4'

services:
  apigateway:
    container_name: c_api_gateway
    image: akiftiryaki/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 6000:6000
    networks:
      - micro_net
      - int_net

  contact.api:
    container_name: c_contact_api
    image: akiftiryaki/contactapi
    build:
      context: .
      dockerfile: Services/ContactAPI/Contact.API/Dockerfile
    ports:
      - 9000:9000
    networks:
      - int_net

  reservation.api:
    container_name: c_reservation_api
    image: akiftiryaki/reservationapi
    build:
      context: .
      dockerfile: Services/ReservationAPI/Reservation.API/Dockerfile
    ports:
      - 7000:7000
    networks:
      - int_net





networks:
  int_net:
    driver: overlay
    internal: true
  micro_net:
    driver: bridge

